#!/bin/bash
set -e

if [ -z "${1}" ]; then
    echo "Specify notebook to run"
    exit 1
fi

# If the notebook is an "output notebook" (*.run.ipynb), which are generated by
# papermill for instance, then do not run it.
pattern="*.run.ipynb"

input_notebook=$1
shift

if [[ $input_notebook == $pattern ]]; then
    echo "Not running output notebook"
    exit 0
fi

# override_nbs=${PHENOPLIER_RUN_NBS_OVERRIDE}
override_nbs=1

# if second argument is a notebook, then it is the output
# notebook filename
if [[ $1 == *.ipynb ]]; then
    output_notebook=${input_notebook%/*}/$1
    shift

    # do not override if output was specified
    override_nbs=0
else
    output_notebook="${input_notebook%.*}.run.ipynb"
fi

# run papermill
papermill \
  --log-output \
  --request-save-on-cell-execute \
  $@ \
  $input_notebook \
  $output_notebook

# Convert to notebook
#
# This is to reduce the notebook final size, which is huge after
# running with papermill.
jupyter nbconvert --to notebook ${output_notebook} --output ${output_notebook##*/}

if [ "${override_nbs}" != "0" ]; then
    mv $output_notebook $input_notebook
    # bash ${GIT_ROOT_DIR}/scripts/convert_ipynb_to_py.sh ${input_notebook}
fi

output_notebook_txt="${output_notebook%.ipynb}.txt"

touch $output_notebook_txt